package com.makarand.medisearch;

import android.content.Intent;
import android.support.annotation.NonNull;
import android.support.v4.content.ContextCompat;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.MotionEvent;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.Toast;

import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.Query;
import com.google.firebase.database.ValueEventListener;
import com.makarand.medisearch.Adapter.MedAdapter;

import java.util.ArrayList;
import java.util.List;

import Models.MedData;

public class MainActivity extends AppCompatActivity {
    LinearLayout row;
    //ImageButton ham;
    EditText searchBar;
    DatabaseReference dbRef;
    List<MedData> medDataList;
    RecyclerView recyclerView;
    MedAdapter medAdapter;
    LinearLayoutManager layoutManager;
    ImageButton searchButton;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        row = findViewById(R.id.row);
        searchBar = findViewById(R.id.search_bar);
        dbRef = FirebaseDatabase.getInstance().getReference("meddata");
        layoutManager = new LinearLayoutManager(this);
        searchButton = findViewById(R.id.search_button);
        //createChip();
        recyclerView = findViewById(R.id.recycler_view);
        recyclerView.setLayoutManager(layoutManager);
        searchButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                String searchText = searchBar.getText().toString().trim();
                if(!searchText.equals(""))
                    searchForMed(searchText);
            }
        });
    }

    private void searchForMed(String searchText) {
        Query query = dbRef.orderByChild("name").startAt(searchText);
        query.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                if(dataSnapshot.exists()){
                    medDataList = new ArrayList<MedData>();
                    for(DataSnapshot dataSnapshot1 : dataSnapshot.getChildren()){
                        final MedData medData = dataSnapshot1.getValue(MedData.class);
                        medDataList.add(medData);
                        medAdapter = new MedAdapter(medDataList, MainActivity.this);
                        recyclerView.setAdapter(medAdapter);
                    }
                }
                else {
                    Toast.makeText(MainActivity.this, "Your search did not turn up any results.", Toast.LENGTH_SHORT).show();
                }
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });
    }

    public void openFeed(View view){
        startActivity(new Intent(this, DataFeed.class));
    }
    private void createChip() {
        Button chip = new Button(getApplicationContext());
        chip.setText("Soemthign");
        chip.setBackground(ContextCompat.getDrawable(getApplicationContext(), R.drawable.chip_background));
        chip.setTextSize(12);
        /*remove following line to ENABLE shadow. However i don't recommend it.*/
        chip.setStateListAnimator(null);
        /*setting height, here 102 is random value generated by trial and error method,
        * I hate that android does not has the literal setHeight function where you can pass dp values*/
        LinearLayout.LayoutParams param = new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT, 108);
        param.leftMargin = 36;
        param.rightMargin = 36;
        chip.setLayoutParams(param);
        row.addView(chip);
    }
}
